jobs:

  - name: deploy-dockercloud-basic_runCI
    type: runCI
    steps:
      - OUT: ddcb-image

  - name: ddcb-manifest
    type: manifest
    steps:
      - IN: ddcb-image
      - TASK: managed
    flags:
      - deploy-dockercloud-basic

  #Docker Cloud deploy job
  - name: ddcb-deploy
    type: deploy
    method: upgrade
    steps:
      - IN: ddcb-manifest
      - IN: ddcb-cluster
    flags:
      - deploy-dockercloud-basic
